### ISSUE TITLE
./download.sh: unpigz: command not found

### ISSUE THREAD

**Issue by medhagitnod** [facebookresearch/Replica-Dataset#12]
I am downloading Replica Dataset in my virtual environment and this error is thrown in my terminal after ‘replica_v1_0.tar.gz.partaq’ is saved. I am using Ubuntu 18.04 and I intend to use these scenes with Habitat-SIM. The error message from my terminal is below:

2019-06-18 18:40:31 (2.48 MB/s) - ‘replica_v1_0.tar.gz.partaq’ saved [1859047808/1859047808]

./download.sh: line 15: unpigz: command not found
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

**Comment by placeforyiming** [comment]
Do you mkdir the directory you want those files to be unzipped?

**Comment by mp3guy** [comment]
I think you need to install the pigz package.

**Comment by jstraub** [comment]
Yes you need to make sure the folder exists and 

Sudo apt-get install pigz 

Pigz is a multithreaded version of gzip. The dataset is pretty big.

**Comment by hzyjerry** [comment]
If you're using Mac OS, here's the steps for installing pigz:

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null`
brew install pigz
```

**Comment by jstraub** [comment]
I added the download instructions for Mac OS to the readme. Closing this issue.

**Comment by smj007** [comment]
Just leaving this information here for future reference. If you are working on a server and do not have root privileges, you can install pigz through **conda**. Refer to this [link](https://anaconda.org/conda-forge/pigz) for the installation.

`conda install -c conda-forge pigz` works for me.
