### ISSUE TITLE
How to export textured meshs to other formats?

### ISSUE THREAD

**Issue by carstenschwede** [facebookresearch/Replica-Dataset#13]
Currently the .PLY format contains colored vertices. Is there an option e.g. using MeshLab to apply the HDR texture atlas and export a textured model to other formats?

**Comment by mp3guy** [comment]
There is not unfortunately, the texture format is custom and not compatible outside of the provided shaders.

**Comment by carstenschwede** [comment]
I see. Thanks for providing colored vertices!

**Comment by quanke0801** [comment]
You can convert vertex color into uv texture: https://steamcommunity.com/sharedfiles/filedetails/?id=1265761945. Note that the vertex colors in ply mesh is not the original texture data, but instead the color samples at only vertex locations. This means the output uv texture will be low res and limited by mesh resolution.

**Comment by mp3guy** [comment]
I would advise against relying on the tonemapped vertex colors. The highest quality appearance comes from the HDR textures, which you can render with the provided shaders.
