### ISSUE TITLE
How to use Replica-Dataset in habitat-sim and habitat-api?

### ISSUE THREAD

**Issue by placeforyiming** [facebookresearch/Replica-Dataset#14]
All the tutorials for datasets are Matterport3D and Gibson.

So, how to use Replica with sim and api? 

For habitat-sim, can I directly use .ply instead of .glb?
    Worked with [notebook tutorial](https://github.com/facebookresearch/habitat-sim/tree/master/notebooks) 

For habitat-api, what should be .yaml,  .json.gz and in directory './data/scene_datasets/' ?

**Comment by jstraub** [comment]
See the README in this repo to see how to view replica through Habitat. We will work on updating the Habitat README to show how to use replica with it. You should only have to point Habitat Sim to the ply file in the Habitat subfolder for a Replica dataset.

**Comment by placeforyiming** [comment]
> See the README in this repo to see how to view replica through Habitat. We will work on updating the Habitat README to show how to use replica with it. You should only have to point Habitat Sim to the ply file in the Habitat subfolder for a Replica dataset.

Yeah, made it work, so how about habitat-api? Since I want to get the intrinsic matrix also and only see a tutorial about it in habitat-api.

Or is there a way to get intrinsic matrix from habitat-sim?

**Comment by jstraub** [comment]
@placeforyiming could you raise that in the github for the habitat-api please.

**Comment by placeforyiming** [comment]
> @placeforyiming could you raise that in the github for the habitat-api please.

Yep, it's [here ] https://github.com/facebookresearch/habitat-api/issues/136)

Also , can I know the default parameters for camera intrinsic matrix? I guess only the focal length should be good for me.

Thanks

**Comment by placeforyiming** [comment]
[how to set intrinsic matrix in habitat-sim:](https://github.com/facebookresearch/habitat-sim/issues/80)
