### ISSUE TITLE
raising "Found no GPUs" error with ReplicaRenderer

### ISSUE THREAD

**Issue by ztzhang** [facebookresearch/Replica-Dataset#18]
Hi,

After successfully compiling the renderer, I'm stuck with the "Found no GPUs" Error raised at EGL.cpp:101. I've installed libegl1-mesa-dev and is using Quadro GP100 with driver version 410.79 and CUDA 10.0.

Any idea what might went wrong?

**Comment by keqpan** [comment]
Hi,
I have observed the same problem. I have working ReplicaViewer, but ReplicaRenderer falls with `Assert failed: numDevices, ReplicaSDK/ptex/EGL.cpp:101 "Found no GPUs" ` 

I have ubuntu 16.04, nvidia driver 410.78 and CUDA Version: 10.0.

@ztzhang could you please, share how you have handled that problem?

**Comment by songlin** [comment]
@ztzhang  Hi, I had the same problem, could you share the solution to fix this error? Thanks
