### ISSUE TITLE
Is office1 supposed to be this purple?

### ISSUE THREAD

**Issue by dhruvbatra** [facebookresearch/Replica-Dataset#21]
What the title says. Are the textures garbled?

![office1](https://user-images.githubusercontent.com/2941091/60390541-ca808f80-9a8d-11e9-814d-878674d2d52c.gif)

**Comment by jstraub** [comment]
this is the texture mapped vertex colored mesh not the PTex textures. Please consider using those.

**Comment by weihaosky** [comment]
@jstraub I am facing the same problem. What do you mean? How to convert it to normal texture? 
Many thanks!

**Comment by jstraub** [comment]
@weihaosky you are looking at the vertex colored mesh of you see the same colors as in the video above. Using the vertex colored mesh is not encouraged. Please use the PTex textured mesh as you can see through the viewer supplied with the SDK. If you are using Replica through AI Habitat: we are working on supporting PTex in AI Habitat.

**Comment by weihaosky** [comment]
@jstraub So for now the color can only be the same with the video above? That's too bad. The light is too strong. Or I can change it in Replica and produce a new .ply with different color and light for Habitat.

**Comment by BryanBo-Cao** [comment]
Same here using AI Habitat. Color in ```office_1``` purple.
