### ISSUE TITLE
Habitat mesh_semantic.ply format

### ISSUE THREAD

**Issue by goopci** [facebookresearch/Replica-Dataset#24]
Is there any documentation on the format for the habitat/mesh_semantic.ply files?
I'm hoping to create my own "dataset" with some .ply files, and I'm not sure how the semantic labels are added to the .ply file.

**Comment by jstraub** [comment]
@erikwijmans can you comment and or provide pointers to the code in Habitat Sim that reads the files?

**Comment by goopci** [comment]
I was able to convert the .ply files to an ascii format, so I think that should be all I need!

**Comment by erikwijmans** [comment]
Loading code in habitat-sim: https://github.com/facebookresearch/habitat-sim/blob/master/src/esp/assets/GenericInstanceMeshData.cpp#L76

**Comment by jstraub** [comment]
Thanks @erikwijmans - closing this for now. Please reopen if needed.
