### ISSUE TITLE
Coordinate space clarification

### ISSUE THREAD

**Issue by PsycoTodd** [facebookresearch/Replica-Dataset#26]
Hello
Just want to see if the mesh are defined in OpenGL space. Also the camera used in the renderer and viewer. Thank you.

**Comment by jstraub** [comment]
meshes and cameras are defined in a world coordinate system.

**Comment by PsycoTodd** [comment]
Thank you. So the world coordinate system is Z as the opposite of the gravity as I saw the mesh.ply in Meshlab?

**Comment by jstraub** [comment]
Yes the convention is that gravity is pointing in -z direction.

**Comment by jstraub** [comment]
I hope that clarified the conventions? If not please reopen =)
