### ISSUE TITLE
Are some scenes supposed to not have ceiling?

### ISSUE THREAD

**Issue by iszihan** [facebookresearch/Replica-Dataset#31]
Seems all the frl_apartments and some other scene do not have ceilings when rendered (see picture). Is this normal?
![frl_apartment_4_82_0_pos1](https://user-images.githubusercontent.com/36280571/61639554-b9303a80-ac69-11e9-956a-5dd71f4897c6.png)

**Comment by jstraub** [comment]
Yes unfortunately the frl_apartment scenes do not have a ceiling.

**Comment by small-zeng** [comment]
Could you provide frl_apartments with  ceilings, thank you
