### ISSUE TITLE
Different world coordinate systems?  Starting point in hotel_0 and office_0 is based on bed, not floor.

### ISSUE THREAD

**Issue by placeforyiming** [facebookresearch/Replica-Dataset#32]
I set the initial state of the robot as the same for all the scenes as follow:

# Set agent state
agent = sim.initialize_agent(sim_settings["default_agent"])
agent_state = habitat_sim.AgentState()
agent_state.position = np.array([0.0, 0.072447, 0.0])
agent_state.rotation = np.quaternion(1, 0.0, 0.0, 0)
agent.set_state(agent_state)

For apartment, it looks good :
![problem_2](https://user-images.githubusercontent.com/22132384/63281907-b41bd680-c27b-11e9-8a85-81234862ade0.png)

However, for the hotel:

![problem_1](https://user-images.githubusercontent.com/22132384/63281933-c0079880-c27b-11e9-901e-4e37a52aa387.png)

I hope the robot can capture images from the same view, so how to handle this situation?

**Comment by placeforyiming** [comment]
I guess x,z coordinates work on 2D map, the height in y direction is depending on the height of the initial point of the robot. If I guess right, what does the sensor position mean? If I want to set the initial point of the robot, should I keep it consistent with the sensor position?


sensors = {
        "color_sensor": {
            "sensor_type": habitat_sim.SensorType.COLOR,
            "resolution": [settings["height"], settings["width"]],
            "position": [0.0, settings["sensor_height"], 0.0],
        },
        "depth_sensor": {
            "sensor_type": habitat_sim.SensorType.DEPTH,
            "resolution": [settings["height"], settings["width"]],
            "position": [0.0, settings["sensor_height"], 0.0],
        },
        "semantic_sensor": {
            "sensor_type": habitat_sim.SensorType.SEMANTIC,
            "resolution": [settings["height"], settings["width"]],
            "position": [0.0, settings["sensor_height"], 0.0],
        },  
    }

**Comment by erikwijmans** [comment]
There is no global coordinate system, each mesh has its own coordinate system with an arbitrary origin.  The sensor position is the position of the sensor _relative_ to the position of the agent, move the agent and the sensors will follow.

**Comment by placeforyiming** [comment]
> There is no global coordinate system, each mesh has its own coordinate system with an arbitrary origin. The sensor position is the position of the sensor _relative_ to the position of the agent, move the agent and the sensors will follow.

Thanks for make sure!
