### ISSUE TITLE
What is the collision mechanism? Will it lead to the wrong calculation of the agent.position?

### ISSUE THREAD

**Issue by placeforyiming** [facebookresearch/Replica-Dataset#33]
![Screenshot_2019-08-19 habitat-sim-demo - Jupyter Notebook](https://user-images.githubusercontent.com/22132384/63292678-39ab8080-c294-11e9-91e1-7eb7c32f8ec2.png)

The action is moving forward with 10cm, but the agent stay there and the agent.position changed

**Comment by erikwijmans** [comment]
This issue can stay here, but for Habitat-API/Habitat-Sim issues (like this and the other), can you post them to  https://github.com/facebookresearch/habitat-sim or https://github.com/facebookresearch/habitat-api?

**Comment by erikwijmans** [comment]
The agent moved between those two images.  Look at the checker pattern on the floor.  10cm is just a small amount.

**Comment by placeforyiming** [comment]
> The agent moved between those two images. Look at the checker pattern on the floor. 10cm is just a small amount.

Yeah, sure. Will do it for future questions.

> This issue can stay here, but for Habitat-API/Habitat-Sim issues (like this and the other), can you post them to https://github.com/facebookresearch/habitat-sim or https://github.com/facebookresearch/habitat-api?
