### ISSUE TITLE
Segmentation Fault (core dumped) -  ReplicaViewer and ReplicaRenderer

### ISSUE THREAD

**Issue by emphos1** [facebookresearch/Replica-Dataset#40]
Hi guys,

I tried to install the ReplicaSDK and could compile it successfully 😃
However, when I tried to run ReplicaViewer I faced a segmentation fault.

> ./build/ReplicaSDK/ReplicaViewer ./apartment_0/mesh.ply ./apartment_0/textures ./apartment_0/glass.sur
> 
> Loaded 15 mirrors
> Segmentation fault (core dumped)

Any idea? I'm using Ubuntu 16.04, 8GB Ram, kernel: Linux 4.15.0-45-generic
I have attached the gdb trace and also the information about the graphics card installed.

![gdb_trace](https://user-images.githubusercontent.com/20356836/69430508-0d414d80-0d36-11ea-8b55-9dc84fd8bc16.png)
![Graphics_Card](https://user-images.githubusercontent.com/20356836/69430509-0d414d80-0d36-11ea-83a2-2aeb8c1090fb.png)

Best,

**Comment by sinakhodadad** [comment]
I have the same error, Does anyone have any suggestion? My ubuntu is 18.04.

**Comment by jstraub** [comment]
Sadly no idea. Do any of the other sequences work? Any thoughts @simesgreen ?

**Comment by atroyn** [comment]
I think I can shed some light on what's going on here, after going through the process of debugging this for myself yesterday. 

Ubuntu (16.04, 18.04) systems with Nvidia drivers may fall back to software rendering, after an upgrade or a driver update. The software renderer does not support OpenGL features needed by Pangolin and shader compilation. This is not tested at compile or run time, and silently segfaults. 

This is related to this bug in Ubuntu: 
https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1752938

Thew workaround;
1. Confirm Ubuntu is using software rendering by 
`glxinfo | grep "OpenGL"` and note that `GL_RENDERER = llvmpipe (LLVM 5.0, 128 bits)`

2. Confirm that Nvidia drivers are present via `nvidia-smi`

3. Remove or comment `/etc/X11/Xsession.d/50_check_unity_support`, which causes the fallback to software rendering.  

This is likely also the cause of: 
https://github.com/facebookresearch/Replica-Dataset/issues/45 
https://github.com/facebookresearch/Replica-Dataset/issues/46
https://github.com/facebookresearch/Replica-Dataset/issues/35

And possibly the cause of:
https://github.com/facebookresearch/Replica-Dataset/issues/36

**Comment by atroyn** [comment]
This is really the responsibility of Pangolin and Ubuntu, and not this project.
