### ISSUE TITLE
failed to uncompress, require a md5sum.txt for each download file

### ISSUE THREAD

**Issue by quark2019** [facebookresearch/Replica-Dataset#48]
Hi, I've run the download  script again and again to make sure full download every file.
However, it always fails to uncompress:
（I'm using win10 Pro， how to fix this error?）

tar -xvzf merge.tar.gz
x apartment_0/
x apartment_0/textures/
x apartment_0/textures/27-color-ptex.hdr
x apartment_0/textures/3-color-ptex.hdr
x apartment_0/textures/13-color-ptex.hdr
x apartment_0/textures/8-color-ptex.hdr
x apartment_0/textures/20-color-ptex.hdr
x apartment_0/textures/16-color-ptex.hdr
x apartment_0/textures/1-color-ptex.hdr
x apartment_0/textures/9-color-ptex.hdr
x apartment_0/textures/25-color-ptex.hdr
x apartment_0/textures/24-color-ptex.hdr
x apartment_0/textures/6-color-ptex.hdr: gzip decompression failed
tar: Error exit delayed from previous errors.

--------------
Is there a md5sum.txt for each download file?  so that user can check the md5sum after download.

**Comment by quark2019** [comment]
update:  here is my md5sum.txt ( failed to uncompress),  any file is wrong?

> md5sum.exe  replica_v1_0.tar.gz.parta*
9f9cca9ea8749c32579119b3ff637961 *replica_v1_0.tar.gz.partaa
a6ea3efb76588dd50923205003e6623f *replica_v1_0.tar.gz.partab
07fe2eec5d3eab7686b0c0dbb26ab2dc *replica_v1_0.tar.gz.partac
bcbeee782b78d9052774593306498106 *replica_v1_0.tar.gz.partad
54bd3f1bbd81e39a3fe0d5cee65f0981 *replica_v1_0.tar.gz.partae
c3c485960ecbb49ce2fdb183865556d7 *replica_v1_0.tar.gz.partaf
553ec538c1dc156d421e1b541af6de6a *replica_v1_0.tar.gz.partag
ad04202298da63343d6fc41bc1ae2ece *replica_v1_0.tar.gz.partah
e34a7f85f49c2c1d05ac0184a3c4dca2 *replica_v1_0.tar.gz.partai
c9d12878dc78c823beaf75a9218da79d *replica_v1_0.tar.gz.partaj
54bd1bb0049d62e686c6764954d049e1 *replica_v1_0.tar.gz.partak
3e59749231ce367263784489adbcc439 *replica_v1_0.tar.gz.partal
9235db1a79d3d4b5dffb38e1d2066d20 *replica_v1_0.tar.gz.partam
31f404fb30559808be18734e14ba972e *replica_v1_0.tar.gz.partan
376a75bdb73b59ea293d0af844f541f8 *replica_v1_0.tar.gz.partao
1a233e4549713867a40df261c49c9169 *replica_v1_0.tar.gz.partap
2e8ae8805b4d6fec7faa75dc91d17d7c *replica_v1_0.tar.gz.partaq

**Comment by Yiming-19** [comment]
Hi, how can you solve this problem? I meet the similar problem that I cannot uncompress the tar.gz file
