### ISSUE TITLE
Category ID -> Category Name Mapping

### ISSUE THREAD

**Issue by BryanBo-Cao** [facebookresearch/Replica-Dataset#49]
I searched the repo and relevant documents trying to find the mapping from Category ID to Category Name but didn't find it. It would be appreciated if someone get direct me to the wiki.

**Comment by erikwijmans** [comment]
All `info_semantic.json` files have an array called `"classes"` that lists all classes.  Each element in that array is a dictionary with keys `"id"` and `"name"` providing this exactly :)

**Comment by BryanBo-Cao** [comment]
> All `info_semantic.json` files have an array called `"classes"` that lists all classes. Each element in that array is a dictionary with keys `"id"` and `"name"` providing this exactly :)

@erikwijmans Thank you for answering all my naive questions :)
