### ISSUE TITLE
Install fail, after run ./build.sh

### ISSUE THREAD

**Issue by placeforyiming** [facebookresearch/Replica-Dataset#5]
make[2]: *** Waiting for unfinished jobs....
[ 20%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/PLYParser.cpp.o
[ 20%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/PTexLib.cpp.o
[ 30%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/EGL.cpp.o
/home/yiming/workspacefordeeplearning/Facebook/Replica-Dataset/ReplicaSDK/ptex/EGL.cpp: In constructor ‘EGLCtx::EGLCtx(bool, int, bool)’:
/home/yiming/workspacefordeeplearning/Facebook/Replica-Dataset/ReplicaSDK/ptex/EGL.cpp:155:16: error: ‘GLEW_ERROR_NO_GLX_DISPLAY’ was not declared in this scope
     if (err == GLEW_ERROR_NO_GLX_DISPLAY) {
                ^
ReplicaSDK/CMakeFiles/ptex.dir/build.make:110: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/ptex/EGL.cpp.o' failed
make[2]: *** [ReplicaSDK/CMakeFiles/ptex.dir/ptex/EGL.cpp.o] Error 1
CMakeFiles/Makefile2:89: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/all' failed
make[1]: *** [ReplicaSDK/CMakeFiles/ptex.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mp3guy** [comment]
The branch / PR will fix this.

**Comment by czha5168** [comment]
Hi mp3guy,

I met similar issues here. Could you please give me some comments or instructions on this? Much apprecaited.
_[ 10%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/EGL.cpp.o
/bin/sh: 1: Syntax error: "(" unexpected
ReplicaSDK/CMakeFiles/ptex.dir/build.make:81: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/ptex/EGL.cpp.o' failed
make[2]: *** [ReplicaSDK/CMakeFiles/ptex.dir/ptex/EGL.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 20%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/PLYParser.cpp.o
/bin/sh: 1: Syntax error: "(" unexpected
ReplicaSDK/CMakeFiles/ptex.dir/build.make:94: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/ptex/PLYParser.cpp.o' failed
make[2]: *** [ReplicaSDK/CMakeFiles/ptex.dir/ptex/PLYParser.cpp.o] Error 2
[ 30%] Building CXX object ReplicaSDK/CMakeFiles/ptex.dir/ptex/PTexLib.cpp.o
/bin/sh: 1: Syntax error: "(" unexpected
ReplicaSDK/CMakeFiles/ptex.dir/build.make:107: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/ptex/PTexLib.cpp.o' failed
make[2]: *** [ReplicaSDK/CMakeFiles/ptex.dir/ptex/PTexLib.cpp.o] Error 2
CMakeFiles/Makefile2:170: recipe for target 'ReplicaSDK/CMakeFiles/ptex.dir/all' failed
make[1]: *** [ReplicaSDK/CMakeFiles/ptex.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2_
