### ISSUE TITLE
info_semantic.json bad information

### ISSUE THREAD

**Issue by K296** [facebookresearch/Replica-Dataset#53]
I'm having trouble with info_semantic data for frl_apartment_3. If you take a look at the abb center position of the indoor-plants only 2 of 3 make sense. This is also a problem for many other objects in that room.

**Comment by erikwijmans** [comment]
The abb is in the coordinate system of the obb is an abb.  You can see how the loading is done by habitat-sim here: https://github.com/facebookresearch/habitat-sim/blob/master/src/esp/scene/ReplicaSemanticScene.cpp#L86.  The obb in habitat-sim has the center in world coordinates for reference.

**Comment by K296** [comment]
Seems like there are a few words to many or to few in your first sentence but I think I understand. Thanks a lot for reference to the code, I tried to look for that line before with noI should be able to find it. I should be able to figure it out now! :)
