### ISSUE TITLE
replica dataset in habitat + assimp

### ISSUE THREAD

**Issue by mmahdavian** [facebookresearch/Replica-Dataset#63]
Hi

I am trying to use replica dataset in habitat and I have used apartment_01.glb which I could find. I am using https://gist.github.com/erikwijmans/1c596183fb8de1e9afd80088b6b5c115 code to generate training dataset and I change the .glb file to the environment that I want. I need to change other replica dataset envs to be able to generate training data as well. But the replica dataset files are .ply format.Do you know how should I use them in habitat? Should I convert them to .glb and then use them or there is a way in habitat to use .ply files too.
By the way, I have tried to convert .ply to .glb by assimp. But when it tries to open it, the environment is all white and I get no error.

Thank You

**Comment by erikwijmans** [comment]
Just point habitat at the `mesh_semantic.ply` file in the `habitat` folder for a given scan.  That glb is a decimated version to have something that is lighter-weight for running on collab.

**Comment by mmahdavian** [comment]
Thank you for your respond @erikwijmans 
The problem is, on that file ,I get following error:
```
assimp export mesh_semantic.ply mesh.glb -fglb2 -embtex

param = mesh.glb
param = -fglb2
param = -embtex
assimp export: select file format: 'glb2' (GL Transmission Format v. 2 (binary))
Launching asset import ...           OK
Validating postprocessing flags ...  OK
ERROR: Failed to load file: Invalid .ply file: Missing format specification
```
But on mesh.ply in main folder I didn't get any error, but as I said it was all white in habitat.

**Comment by mmahdavian** [comment]
@erikwijmans 
I was able to solve the last problem by deleting a line in .ply file. 
The line was "comment replica-instance-mesh-format v0"
Now that I deleted it, assimp can create a .glb file for me. But still it only show a white environment in habitat. Can I know which version or commit of [assimp](https://github.com/assimp/assimp) are you using? Their current master branch doesn't compile and I used an older commit. It might be the problem.

Thank You

**Comment by erikwijmans** [comment]
Sorry if I wasn't clear, there is no need to convert the ply files to glbs.  Just use `mesh_semantic.ply` directly with habitat.  

In that script, change `scenes = glob.glob("./data/scene_datasets/gibson/*.glb")` to `scenes = glob.glob("./data/scene_datasets/replica/*/habitat/mesh_semantic.ply")`.

**Comment by mmahdavian** [comment]
Thanks a lot @erikwijmans . Just to complete your answer I think your code needs a .navmesh version of the .ply too. I got that from habitat_sim/build/utils/data/datatool/datatool create_navmesh <file>.ply <file>.navmesh

**Comment by erikwijmans** [comment]
.navmesh files should already be present in that `habitat` folder for the replica dataset

**Comment by mmahdavian** [comment]
@erikwijmans  there is a mesh_preseg_semantic.navmesh file that I thought is related to mesh_preseg_semantic.ply. Can it be used for mesh_semantic.ply too?

**Comment by erikwijmans** [comment]
There should be one for each already

**Comment by mmahdavian** [comment]
Sorry.You were right
