### ISSUE TITLE
Segmentation fault for ReplicaRender, any advanced tutorial?

### ISSUE THREAD

**Issue by placeforyiming** [facebookresearch/Replica-Dataset#8]
1. Found ReplicaViewer under ./build/ReplicaSDK, not ./build/bin

2.  Successfully got into it by running:    ./build/ReplicaSDK/ReplicaViewer  ./apartment_0/mesh.ply  ./apartment_0/textures

3. Got segmentation fault by running :   ./build/ReplicaSDK/ReplicaRenderer  ./apartment_0/mesh.ply   ./apartment_0/textures ./apartment_0/glass.sur

This is definitely a very useful dataset for real world robot, so I'm curious is there a more advanced tutorial? For my case, I want to get consecutive images, depth label and camera pose, but I have no idea where should I start.

**Comment by mp3guy** [comment]
Can you provide some more details about the platform you're running on? Operating system, kernel, graphics card and driver versions? Virtual machine?

**Comment by placeforyiming** [comment]
> Can you provide some more details about the platform you're running on? Operating system, kernel, graphics card and driver versions? Virtual machine?

Thanks for quick reply!
I solved this problem by running:
`sudo apt install libegl1-mesa-dev`

Still confused how can we get data from the environment. Should we install habitat-sim as the tool? Or any tutorials? Thanks

**Comment by mp3guy** [comment]
ReplicaRenderer will output jpg images and png depth maps of a simple translational trajectory. If you program more complicated trajectories they will be rendered. Or you can also try the AI Habitat software.

**Comment by placeforyiming** [comment]
Meet the segmentation fault again, have no idea....

1. System : Ubuntu 16.04
2. Graphic Card:  Quadro P2000
3. Driver :  415.27
4. CUDA Version: 10.0
5. kernel : 4.15.0-51-generic

`./build/ReplicaSDK/ReplicaViewer ./Replica_data/apartment_0/mesh.ply ./Replica_data/apartment_0/textures ./Replica_data/apartment_0/glass.sur`  works.

`./build/ReplicaSDK/ReplicaRenderer ./Replica_data/apartment_0/mesh.ply ./Replica_data/apartment_0/textures ./Replica_data/apartment_0/glass.sur` gives me "Segmentation fault"

I guess should I mention a directory to save the rendered images?

**Comment by mp3guy** [comment]
A directory isn't required. Would you be able to run ReplicaRenderer in gdb and show me the output stack back trace when it segfaults?

**Comment by placeforyiming** [comment]
> A directory isn't required. Would you be able to run ReplicaRenderer in gdb and show me the output stack back trace when it segfaults?

I'm sorry I'm not very familiar with debugging in c++, so I plan to change to docker. I think there should be no system errors with docker. 

Just close this one, thanks for quick reply.

**Comment by xiong224** [comment]
I have met the same problem. After I running 'sudo apt install libegl1-mesa-dev', it stil got the same error of 'segmentation fault'. If you could provide the detailed solution? Thanks very much.
