### ISSUE TITLE
Rendering in remote server

### ISSUE THREAD

**Issue by mreyarea-fy** [facebookresearch/Replica-Dataset#82]
Hi,

I am trying to render Replica in a remote headless server. I kept on running into the same error all the time. Any idea why this is and how can I fix it?

`Can't initialize EGL GLEW GLX display, may crash!`

**Comment by mp3guy** [comment]
Does it actually crash or just print that warning and still function?

**Comment by mreyarea-fy** [comment]
Yes, sorry. I was running a minimal script just to check some stuff and it didn't do anything beyond that point. If I run `render.cpp` it prompts that error as well but it keeps rendering. Cheers!
