### ISSUE TITLE
GLSL 3.2ES support

### ISSUE THREAD

**Issue by BITVoyager** [facebookresearch/Replica-Dataset#9]
Hi. Thanks for releasing the dataset. I was wondering if I can use GLSL 3.2ES for the shaders. Thanks.

**Comment by mp3guy** [comment]
You can try replacing the version used in the shaders with this version and see if it just works. There might be some small syntax changes you need to make.

**Comment by BITVoyager** [comment]
After some experiments, we found that adapting the shaders to OpenGL ES versions is not trivial. We finally run the executable with OpenGL 4.5 and everything is OK.
