### ISSUE TITLE
Unable to load Replica scene in Habitat Sim

### ISSUE THREAD

**Issue by joeylitalien** [facebookresearch/Replica-Dataset#90]
Hi,

I've installed [Habitat-Sim](https://github.com/facebookresearch/habitat-sim) successfully and I am able to view and renderer the [example scene](https://github.com/facebookresearch/habitat-sim#testing). However, whenever I try to open a Replica scene, I get the following error:

```
$ habitat-viewer --dataset path/to/replica.scene_dataset_config.json -- office_0
...
[13:44:16:220066]:[Assets] PTexMeshData.cpp(857)::uploadBuffersToGPU : Calculating mesh adjacency...
[13:44:16:532753]:[Assets] PTexMeshData.cpp(904)::uploadBuffersToGPU : loading atlas textures:
[13:44:16:532824]:[Assets] PTexMeshData.cpp(913)::uploadBuffersToGPU : Loading atlas 1 / 4 from office_0/habitat/../textures/0-color-ptex.hdr .
[13:44:16:989544]:[Assets] PTexMeshData.cpp(913)::uploadBuffersToGPU : Loading atlas 2 / 4 from office_0/habitat/../textures/1-color-ptex.hdr .
[13:44:17:314004]:[Assets] PTexMeshData.cpp(913)::uploadBuffersToGPU : Loading atlas 3 / 4 from office_0/habitat/../textures/2-color-ptex.hdr .
[13:44:17:621121]:[Assets] PTexMeshData.cpp(913)::uploadBuffersToGPU : Loading atlas 4 / 4 from office_0/habitat/../textures/3-color-ptex.hdr .
GL::AbstractShaderProgram::link(): linking failed with the following message:
Geometry info
-------------
(0) : error C6022: No input primitive type
(0) : error C6029: No output primitive type
Assertion link() failed at /opt/conda/envs/py37/conda-bld/habitat-sim_1670543878226/work/src/esp/gfx/PTexMeshShader.cpp:65
Aborted (core dumped)
```

This seems to be a Replica dataset problem because I don't have this issue with other datasets (e.g. ScanNet), hence why I am posting here. I'm running Ubuntu 20.04 with an NVIDIA Titan V (Driver Version: 510.39.01) along with OpenGL v4.6.

Any help would be greatly appreciated.

**Comment by liangsusan-git** [comment]
Hi,

I got the same error information. Did you solve this problem?

**Comment by joeylitalien** [comment]
Hi @liangsusan-git,

It's been a while so I cannot reproduce exactly how I solved the problem. However, I remember realizing that the documentation was wrong and that you need to pass the `.ply` from Replica instead of the scene name (or the directory containing the `.ply`, not sure). Hopefully this is enough info to fix it.

**Comment by liangsusan-git** [comment]
Thank you! After passing the ply path of a scene, I can run the code with no error.

**Comment by amaizr** [comment]
ran into this too but for me the fix was to patch `src/esp/gfx/PTexMeshShader.cpp` to compile geometry shader w/:

```diff
diff --git a/src/esp/gfx/PTexMeshShader.cpp b/src/esp/gfx/PTexMeshShader.cpp
index 949774a8..2ed24fda 100644
--- a/src/esp/gfx/PTexMeshShader.cpp
+++ b/src/esp/gfx/PTexMeshShader.cpp
@@ -58,7 +58,7 @@ PTexMeshShader::PTexMeshShader() {
 #endif
   frag.addSource(rs.getString("ptex-default-gl410.frag"));
 
-  CORRADE_INTERNAL_ASSERT_OUTPUT(vert.compile() && frag.compile());
+  CORRADE_INTERNAL_ASSERT_OUTPUT(vert.compile() && geom.compile() && frag.compile());
 
   attachShaders({vert, geom, frag});
```

tried passing different paths but didnt work.

**Comment by ariannaliu** [comment]
> Thank you! After passing the ply path of a scene, I can run the code with no error.

Hi! I still meet this problem :(

May I know which .ply file you passed?

**Comment by ariannaliu** [comment]
> ```diff
> CORRADE_INTERNAL_ASSERT_OUTPUT(vert.compile() && geom.compile() && frag.compile());
> ```

Okay, I figured out by passing the path of "/path_to_replicadataset/habitat/mesh_semantic.ply"
Thank you so much

**Comment by haoming-Yu** [comment]
> "

well, although using mesh_semantic.ply can run the program, but the reflections and various lights in replica datasets seem to be ignored by doing this on my pc. I think it's not the proper way to test the data? In my case I need to compile the geometry shader to enable full replica reading by using json file.

**Comment by haoming-Yu** [comment]
> > CORRADE_INTERNAL_ASSERT_OUTPUT(vert.compile() && geom.compile() && frag.compile());
> 
> Okay, I figured out by passing the path of "/path_to_replicadataset/habitat/mesh_semantic.ply" Thank you so much

Well, it seems that doing this will cause the various lighting effects and reflections to vanish on my machine. The better solution seems to link the geometry shader with vert and frag.

**Comment by Berenhill** [comment]
> > CORRADE_INTERNAL_ASSERT_OUTPUT(vert.compile() && geom.compile() && frag.compile());
> 
> Okay, I figured out by passing the path of "/path_to_replicadataset/habitat/mesh_semantic.ply" Thank you so much

Hello！I meet this problem. Could you give something more detailed?
